diffusion_pipeline:
  target: diffusion.DiffusionPipeline.DiffusionPipeline
  params:
    model:
      target: models.DiT.DiT  # 可替换为 diffusion.models.UNet
      params:
        input_size: 32
        input_ch: 4
        patch_size: 2
        n_ch: 512
        n_blocks: 8
        num_heads: 8
        pe: "rope"
    scheduler:
      # --- Switch to FlowMatchingScheduler ---
      target: diffusion.FlowMatchingScheduler.FlowMatchingScheduler
      params: {}

training:
  title: "flow_matching_model"
  epochs: 500
  batch_size: 128
  lr: 1.0e-4
  save_every: 100

checkpoint:
  load: true
  path: "/data1/yangyanliang/Diffusion-Model/score_100.pth"

data:
  path: "/data1/yangyanliang/data/latents.lmdb/"

# --- Sampling Arguments ---
sampling:
  shape: [8, 4, 32, 32]
  n_steps: 100  # Flow matching often requires fewer steps
  output_dir: "./samples"


# --- Checkpoint Paths for Sampling ---
checkpoints:
  pipeline_path: "/data1/yangyanliang/Diffusion-Model/flow_matching_model_500.pth"
  vae_path: "/data1/yangyanliang/Diffusion-Model/autoencoderkl_finetuned_celeba_hq2_5/"
