diffusion_pipeline:
  target: diffusion.DiffusionPipeline.DiffusionPipeline
  params:
    model:
      target: models.DiT.DiT
      params:
        input_size: 32
        input_ch: 4
        patch_size: 2
        n_ch: 512
        n_blocks: 8
        num_heads: 8
        pe: "rope"
    scheduler:
      target: diffusion.SubVPSDEScheduler.SubVPSDEScheduler
      params:
        beta_min: 0.001
        beta_max: 10.0
        prediction_type: 's'

training:
  title: "subvpsde"
  epochs: 500
  batch_size: 128
  lr: 1.0e-4
  save_every: 100

checkpoint:
  load: false
  path: "/data1/yangyanliang/Diffusion-Model/subvpsde_500.pth"

data:
  path: "/data1/yangyanliang/data/latents.lmdb/"

# --- Sampling Arguments ---
sampling:
  shape: [16, 4, 32, 32]
  n_steps: 1000
  corrector_steps: 1
  target_snr: 0.16
  output_dir: "./samples"


# --- Checkpoint Paths for Sampling ---
checkpoints:
  pipeline_path: "/data1/yangyanliang/Diffusion-Model/subvpsde_500.pth"
  vae_path: "/data1/yangyanliang/Diffusion-Model/autoencoderkl_finetuned_celeba_hq2_5/"
