diffusion_pipeline:
  target: diffusion.DiffusionPipeline.DiffusionPipeline
  params:
    model:
      target: models.DiT.DiT
      params:
        input_size: 32
        input_ch: 4
        patch_size: 2
        n_ch: 512
        n_blocks: 8
        num_heads: 8
        pe: "rope"
    scheduler:
      target: diffusion.VESDEScheduler.VESDEScheduler
      params:
        sigma_min: 0.01
        sigma_max: 378.0
        prediction_type: 's'

training:
  title: "vesde"
  epochs: 1500
  batch_size: 128
  lr: 1.0e-4
  save_every: 100

checkpoint:
  load: true
  path: "/data1/yangyanliang/Diffusion-Model/vesde_1000.pth"

data:
  path: "/data1/yangyanliang/data/latents.lmdb/"

# --- Sampling Arguments ---
sampling:
  shape: [64, 4, 32, 32]
  n_steps: 2000
  corrector_steps: 1
  target_snr: 0.03
  sampler_type: 'sde'
  output_dir: "./samples"


# --- Checkpoint Paths for Sampling ---
checkpoints:
  pipeline_path: "/data1/yangyanliang/Diffusion-Model/vesde_1200.pth"
  vae_path: "/data1/yangyanliang/Diffusion-Model/autoencoderkl_finetuned_celeba_hq2_5/"
