diffusion_pipeline:
  target: diffusion.DiffusionPipeline.DiffusionPipeline
  params:
    model:
      target: models.DiT.DiT
      params:
        input_size: 32
        input_ch: 4
        patch_size: 2
        n_ch: 512
        n_blocks: 8
        num_heads: 8
        pe: "rope"
        has_cond: false
    scheduler:
      target: diffusion.VPSDEScheduler.VPSDEScheduler
      params:
        beta_min: 0.01
        beta_max: 20.0
        prediction_type: 's'

training:
  title: "vpsde_ver3"
  epochs: 1000
  batch_size: 128
  lr: 1.0e-4
  save_every: 100

checkpoint:
  load: false
  path: "/data1/yangyanliang/Diffusion-Model/vpsde_500.pth"

data:
  path: "/data1/yangyanliang/data/latents.lmdb/"

# --- Sampling Arguments ---
sampling:
  shape: [8, 4, 32, 32]
  n_steps: 1000
  corrector_steps: 2
  target_snr: 0.05
  sampler_type: 'sde'


# --- Checkpoint Paths for Sampling ---
checkpoints:
  pipeline_path: "/data1/yangyanliang/Diffusion-Model/vpsde_score_1000.pth"
  vae_path: "path/to/your/autoencoderkl/"
